/* ============================================
   BASS PHONK - Constants & Demo Data
   ============================================ */

/** Genre list with colors and icons */
export const GENRES = [
  { id: 'brazilian', name: 'Brazilian Phonk', color: '#FF0040', emoji: '🇧🇷' },
  { id: 'drift', name: 'Drift Phonk', color: '#BF00FF', emoji: '🏎️' },
  { id: 'memphis', name: 'Memphis', color: '#00FFFF', emoji: '💀' },
  { id: 'cowbell', name: 'Cowbell', color: '#FF00DE', emoji: '🔔' },
  { id: 'dark', name: 'Dark Phonk', color: '#FF6B00', emoji: '🌑' },
  { id: 'aggressive', name: 'Aggressive', color: '#FF0040', emoji: '⚡' },
  { id: 'house', name: 'House Phonk', color: '#00FF88', emoji: '🏠' },
  { id: 'gym', name: 'Gym Phonk', color: '#FFD600', emoji: '💪' },
  { id: 'wave', name: 'Wave', color: '#0088FF', emoji: '🌊' },
  { id: 'tiktok', name: 'TikTok Phonk', color: '#FF00DE', emoji: '📱' },
];

/** EQ Presets */
export const EQ_PRESETS = [
  { name: 'Flat', values: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0] },
  { name: 'Bass Boost', values: [10, 8, 6, 3, 0, 0, 0, 0, 0, 0] },
  { name: 'Bass Monster', values: [12, 10, 8, 5, 2, 0, -1, -2, -1, 0] },
  { name: 'Treble Boost', values: [0, 0, 0, 0, 0, 2, 4, 6, 8, 10] },
  { name: 'V-Shape', values: [8, 6, 2, -1, -3, -3, -1, 2, 6, 8] },
  { name: 'Vocal', values: [-2, -1, 0, 3, 6, 6, 3, 0, -1, -2] },
  { name: 'Electronic', values: [8, 6, 2, 0, -2, 2, 0, 2, 6, 8] },
  { name: 'Deep', values: [10, 8, 4, 1, -2, -4, -2, 0, 2, 4] },
  { name: 'Night Drive', values: [6, 5, 3, 2, 0, -1, 0, 2, 4, 6] },
  { name: 'Car Audio', values: [10, 8, 5, 2, 0, 0, 1, 3, 5, 7] },
];

/** EQ Band frequencies */
export const EQ_BANDS = [32, 64, 125, 250, 500, 1000, 2000, 4000, 8000, 16000];

/** Demo tracks */
export const DEMO_TRACKS = [
  {
    id: '1',
    title: 'Why Not',
    artist: 'GHOSTFACE PLAYA',
    album: 'Phonk Hits Vol. 1',
    duration: 198,
    bpm: 140,
    genre: 'memphis',
    cover: 'https://picsum.photos/300/300?random=1',
    plays: 45200000,
    liked: true,
    audioUrl: '',
  },
  {
    id: '2',
    title: 'Murder In My Mind',
    artist: 'KORDHELL',
    album: 'Murder In My Mind',
    duration: 156,
    bpm: 145,
    genre: 'aggressive',
    cover: 'https://picsum.photos/300/300?random=2',
    plays: 892000000,
    liked: false,
    audioUrl: '',
  },
  {
    id: '3',
    title: 'PHONK WALK',
    artist: 'FREDEL',
    album: 'Phonk Walk',
    duration: 174,
    bpm: 138,
    genre: 'brazilian',
    cover: 'https://picsum.photos/300/300?random=3',
    plays: 320000000,
    liked: true,
    audioUrl: '',
  },
  {
    id: '4',
    title: 'METAMORPHOSIS',
    artist: 'INTERWORLD',
    album: 'Metamorphosis',
    duration: 210,
    bpm: 150,
    genre: 'dark',
    cover: 'https://picsum.photos/300/300?random=4',
    plays: 560000000,
    liked: false,
    audioUrl: '',
  },
  {
    id: '5',
    title: 'DRIFTING',
    artist: 'DXRK ダーク',
    album: 'Drifting',
    duration: 185,
    bpm: 142,
    genre: 'drift',
    cover: 'https://picsum.photos/300/300?random=5',
    plays: 180000000,
    liked: true,
    audioUrl: '',
  },
  {
    id: '6',
    title: 'COWBELL WARRIOR',
    artist: 'TEEKKARI',
    album: 'Cowbell Season',
    duration: 165,
    bpm: 135,
    genre: 'cowbell',
    cover: 'https://picsum.photos/300/300?random=6',
    plays: 78000000,
    liked: false,
    audioUrl: '',
  },
  {
    id: '7',
    title: 'CLOSE EYES',
    artist: 'DVRST',
    album: 'Close Eyes',
    duration: 192,
    bpm: 148,
    genre: 'drift',
    cover: 'https://picsum.photos/300/300?random=7',
    plays: 1200000000,
    liked: true,
    audioUrl: '',
  },
  {
    id: '8',
    title: 'NIGHT LOVELL TYPE',
    artist: 'HXRXKILLER',
    album: 'Dark Sessions',
    duration: 203,
    bpm: 155,
    genre: 'dark',
    cover: 'https://picsum.photos/300/300?random=8',
    plays: 92000000,
    liked: false,
    audioUrl: '',
  },
  {
    id: '9',
    title: 'GYM PHONK ANTHEM',
    artist: 'KORDHELL',
    album: 'Gym Phonk Vol 2',
    duration: 178,
    bpm: 160,
    genre: 'gym',
    cover: 'https://picsum.photos/300/300?random=9',
    plays: 240000000,
    liked: true,
    audioUrl: '',
  },
  {
    id: '10',
    title: 'BRAZILIAN BASS',
    artist: 'MC DANINHO',
    album: 'Baile Phonk',
    duration: 195,
    bpm: 130,
    genre: 'brazilian',
    cover: 'https://picsum.photos/300/300?random=10',
    plays: 156000000,
    liked: false,
    audioUrl: '',
  },
  {
    id: '11',
    title: 'EMPIRE',
    artist: 'KORDHELL',
    album: 'Empire',
    duration: 168,
    bpm: 152,
    genre: 'aggressive',
    cover: 'https://picsum.photos/300/300?random=11',
    plays: 430000000,
    liked: true,
    audioUrl: '',
  },
  {
    id: '12',
    title: 'SAHARA',
    artist: 'HENSONN',
    album: 'Sahara',
    duration: 187,
    bpm: 143,
    genre: 'drift',
    cover: 'https://picsum.photos/300/300?random=12',
    plays: 210000000,
    liked: false,
    audioUrl: '',
  },
  {
    id: '13',
    title: 'SLAY!',
    artist: 'ETERNXLKZ',
    album: 'Slay!',
    duration: 152,
    bpm: 148,
    genre: 'tiktok',
    cover: 'https://picsum.photos/300/300?random=13',
    plays: 680000000,
    liked: true,
    audioUrl: '',
  },
  {
    id: '14',
    title: 'RAVE',
    artist: 'DXRK ダーク',
    album: 'Dark Rave',
    duration: 201,
    bpm: 155,
    genre: 'house',
    cover: 'https://picsum.photos/300/300?random=14',
    plays: 145000000,
    liked: false,
    audioUrl: '',
  },
  {
    id: '15',
    title: 'MIDNIGHT DRIFT',
    artist: 'PLAYAPHONK',
    album: 'Midnight',
    duration: 189,
    bpm: 140,
    genre: 'drift',
    cover: 'https://picsum.photos/300/300?random=15',
    plays: 330000000,
    liked: true,
    audioUrl: '',
  },
  {
    id: '16',
    title: 'MEMORY REBOOT',
    artist: 'VOJ & NARVENT',
    album: 'Memory Reboot',
    duration: 216,
    bpm: 136,
    genre: 'wave',
    cover: 'https://picsum.photos/300/300?random=16',
    plays: 780000000,
    liked: true,
    audioUrl: '',
  },
  {
    id: '17',
    title: 'FUNK DO GRAVE',
    artist: 'DJ FKU',
    album: 'Grave Bass',
    duration: 172,
    bpm: 132,
    genre: 'brazilian',
    cover: 'https://picsum.photos/300/300?random=17',
    plays: 89000000,
    liked: false,
    audioUrl: '',
  },
  {
    id: '18',
    title: 'OVERRIDE',
    artist: 'KSLV',
    album: 'Override',
    duration: 194,
    bpm: 158,
    genre: 'aggressive',
    cover: 'https://picsum.photos/300/300?random=18',
    plays: 520000000,
    liked: true,
    audioUrl: '',
  },
  {
    id: '19',
    title: 'TOKYO DRIFT PHONK',
    artist: 'DRIFTMANE',
    album: 'Tokyo Sessions',
    duration: 183,
    bpm: 145,
    genre: 'drift',
    cover: 'https://picsum.photos/300/300?random=19',
    plays: 275000000,
    liked: false,
    audioUrl: '',
  },
  {
    id: '20',
    title: 'PUSH IT',
    artist: 'KORDHELL',
    album: 'Push It',
    duration: 162,
    bpm: 165,
    genre: 'gym',
    cover: 'https://picsum.photos/300/300?random=20',
    plays: 195000000,
    liked: true,
    audioUrl: '',
  },
  {
    id: '21',
    title: 'VILLAIN',
    artist: 'K!NG Z3US',
    album: 'Villain Arc',
    duration: 208,
    bpm: 138,
    genre: 'dark',
    cover: 'https://picsum.photos/300/300?random=21',
    plays: 110000000,
    liked: false,
    audioUrl: '',
  },
  {
    id: '22',
    title: 'NEON BLADE',
    artist: 'MOON DEITY',
    album: 'Neon Blade',
    duration: 176,
    bpm: 142,
    genre: 'drift',
    cover: 'https://picsum.photos/300/300?random=22',
    plays: 950000000,
    liked: true,
    audioUrl: '',
  },
  {
    id: '23',
    title: 'AUTOMOTIVO BIBI',
    artist: 'MC GW',
    album: 'Automotivo',
    duration: 159,
    bpm: 130,
    genre: 'brazilian',
    cover: 'https://picsum.photos/300/300?random=23',
    plays: 420000000,
    liked: false,
    audioUrl: '',
  },
  {
    id: '24',
    title: 'SHADOW',
    artist: 'RXBYN',
    album: 'Shadow EP',
    duration: 191,
    bpm: 150,
    genre: 'dark',
    cover: 'https://picsum.photos/300/300?random=24',
    plays: 67000000,
    liked: true,
    audioUrl: '',
  },
];

/** Demo playlists */
export const DEMO_PLAYLISTS = [
  {
    id: 'p1',
    name: 'Night Drive 🌃',
    description: 'Late night cruising vibes',
    cover: 'https://picsum.photos/300/300?random=30',
    trackCount: 45,
    plays: 2400000,
    gradient: 'linear-gradient(135deg, #BF00FF, #0088FF)',
    category: 'mood',
  },
  {
    id: 'p2',
    name: 'Gym Beast Mode 💪',
    description: 'Maximum aggression for PRs',
    cover: 'https://picsum.photos/300/300?random=31',
    trackCount: 68,
    plays: 5600000,
    gradient: 'linear-gradient(135deg, #FF0040, #FF6B00)',
    category: 'activity',
  },
  {
    id: 'p3',
    name: 'Drift Session 🏎️',
    description: 'Sideways only',
    cover: 'https://picsum.photos/300/300?random=32',
    trackCount: 52,
    plays: 3200000,
    gradient: 'linear-gradient(135deg, #FF00DE, #BF00FF)',
    category: 'mood',
  },
  {
    id: 'p4',
    name: 'Gaming Focus 🎮',
    description: 'Clutch time soundtrack',
    cover: 'https://picsum.photos/300/300?random=33',
    trackCount: 38,
    plays: 4100000,
    gradient: 'linear-gradient(135deg, #00FFFF, #00FF88)',
    category: 'activity',
  },
  {
    id: 'p5',
    name: 'Car Meet 🔥',
    description: 'Pull up with bass',
    cover: 'https://picsum.photos/300/300?random=34',
    trackCount: 55,
    plays: 1800000,
    gradient: 'linear-gradient(135deg, #FF0040, #BF00FF)',
    category: 'mood',
  },
  {
    id: 'p6',
    name: 'TikTok Bangers 📱',
    description: 'Viral phonk hits',
    cover: 'https://picsum.photos/300/300?random=35',
    trackCount: 42,
    plays: 8900000,
    gradient: 'linear-gradient(135deg, #FF00DE, #00FFFF)',
    category: 'trending',
  },
  {
    id: 'p7',
    name: 'Memphis Underground 💀',
    description: 'Raw Memphis sound',
    cover: 'https://picsum.photos/300/300?random=36',
    trackCount: 34,
    plays: 920000,
    gradient: 'linear-gradient(135deg, #666, #000)',
    category: 'genre',
  },
  {
    id: 'p8',
    name: 'Workout Rage 🔥',
    description: 'No mercy, no rest',
    cover: 'https://picsum.photos/300/300?random=37',
    trackCount: 60,
    plays: 3700000,
    gradient: 'linear-gradient(135deg, #FF6B00, #FFD600)',
    category: 'activity',
  },
];

/** Demo artists */
export const DEMO_ARTISTS = [
  { id: 'a1', name: 'KORDHELL', avatar: 'https://picsum.photos/200/200?random=40', followers: 8500000, verified: true },
  { id: 'a2', name: 'DVRST', avatar: 'https://picsum.photos/200/200?random=41', followers: 12000000, verified: true },
  { id: 'a3', name: 'GHOSTFACE PLAYA', avatar: 'https://picsum.photos/200/200?random=42', followers: 3200000, verified: true },
  { id: 'a4', name: 'DXRK ダーク', avatar: 'https://picsum.photos/200/200?random=43', followers: 5600000, verified: true },
  { id: 'a5', name: 'INTERWORLD', avatar: 'https://picsum.photos/200/200?random=44', followers: 4100000, verified: true },
  { id: 'a6', name: 'FREDEL', avatar: 'https://picsum.photos/200/200?random=45', followers: 2800000, verified: false },
  { id: 'a7', name: 'PLAYAPHONK', avatar: 'https://picsum.photos/200/200?random=46', followers: 6700000, verified: true },
  { id: 'a8', name: 'MOON DEITY', avatar: 'https://picsum.photos/200/200?random=47', followers: 9800000, verified: true },
  { id: 'a9', name: 'HENSONN', avatar: 'https://picsum.photos/200/200?random=48', followers: 3400000, verified: true },
  { id: 'a10', name: 'ETERNXLKZ', avatar: 'https://picsum.photos/200/200?random=49', followers: 7200000, verified: true },
];

/** Wallpaper categories */
export const WALLPAPER_CATEGORIES = [
  { id: 'cars', name: 'Cars', emoji: '🏎️' },
  { id: 'anime', name: 'Anime', emoji: '🎌' },
  { id: 'cyberpunk', name: 'Cyberpunk', emoji: '🌃' },
  { id: 'jdm', name: 'JDM', emoji: '🇯🇵' },
  { id: 'supra', name: 'Supra', emoji: '🔰' },
  { id: 'drift', name: 'Drift', emoji: '💨' },
];

/** Demo wallpapers */
export const DEMO_WALLPAPERS = Array.from({ length: 24 }, (_, i) => ({
  id: `w${i + 1}`,
  url: `https://picsum.photos/1080/1920?random=${60 + i}`,
  thumbnail: `https://picsum.photos/400/700?random=${60 + i}`,
  category: WALLPAPER_CATEGORIES[i % WALLPAPER_CATEGORIES.length].id,
  downloads: Math.floor(Math.random() * 50000) + 5000,
  likes: Math.floor(Math.random() * 10000) + 1000,
}));

/** Visualizer modes */
export const VISUALIZER_MODES = [
  { id: 'bars', name: 'Spectrum Bars', icon: '📊' },
  { id: 'wave', name: 'Waveform', icon: '🌊' },
  { id: 'circular', name: 'Circular', icon: '⭕' },
  { id: 'particles', name: 'Particles', icon: '✨' },
];

/** Community leaderboard */
export const DEMO_LEADERBOARD = [
  { rank: 1, username: 'DriftKing_99', avatar: 'https://picsum.photos/100/100?random=70', points: 45200, badge: '👑', level: 42 },
  { rank: 2, username: 'PhonkLord', avatar: 'https://picsum.photos/100/100?random=71', points: 38900, badge: '🔥', level: 38 },
  { rank: 3, username: 'BassHead_x', avatar: 'https://picsum.photos/100/100?random=72', points: 34100, badge: '💎', level: 35 },
  { rank: 4, username: 'NightRider', avatar: 'https://picsum.photos/100/100?random=73', points: 28700, badge: '⚡', level: 31 },
  { rank: 5, username: 'MemphisOG', avatar: 'https://picsum.photos/100/100?random=74', points: 25300, badge: '💀', level: 28 },
  { rank: 6, username: 'RXVE_Culture', avatar: 'https://picsum.photos/100/100?random=75', points: 22100, badge: '🎵', level: 25 },
  { rank: 7, username: 'Turbo_Dan', avatar: 'https://picsum.photos/100/100?random=76', points: 19800, badge: '🏎️', level: 22 },
  { rank: 8, username: 'GymRat420', avatar: 'https://picsum.photos/100/100?random=77', points: 17500, badge: '💪', level: 20 },
  { rank: 9, username: 'VaporMane', avatar: 'https://picsum.photos/100/100?random=78', points: 15200, badge: '🌊', level: 18 },
  { rank: 10, username: 'CowbellKid', avatar: 'https://picsum.photos/100/100?random=79', points: 13900, badge: '🔔', level: 16 },
];

/** Premium features */
export const PREMIUM_FEATURES = [
  { icon: '🔊', title: 'Extreme Bass Boost', description: 'Unlock the deepest bass levels with our custom sub-bass engine' },
  { icon: '🎧', title: '8D Audio', description: 'Immersive 360° spatial audio that moves around your head' },
  { icon: '📊', title: 'Advanced EQ', description: '10-band parametric equalizer with custom presets' },
  { icon: '🎨', title: 'Exclusive Wallpapers', description: 'Premium 4K wallpapers updated weekly' },
  { icon: '⬇️', title: 'Offline Mode', description: 'Download unlimited tracks for offline listening' },
  { icon: '🚫', title: 'No Ads', description: 'Zero interruptions, pure phonk experience' },
  { icon: '🎵', title: 'Lossless Audio', description: 'Studio quality audio up to 24-bit/192kHz' },
  { icon: '🏎️', title: 'Car Mode Pro', description: 'Enhanced car mode with speedometer sync' },
];
